### ISSUE TITLE
Exposed WIFI SSID, Password and Adafruit Credentials

### ISSUE THREAD

**Issue by vince00000** [RenzJoal08/iLocate-Wearable-Tracker-Device#1]
Hello po. Nakita ko lang po na hardcoded po yung ilang credentials niyo. Pwede po siya ma-abuse kapag nakapublic. Ihiwalay niyo nalang po siya in a separate config file tapos isama niyo sa .gitignore para di masama sa pagcommit sa github. Thanks.

**Comment by RenzJoal08** [comment]
Hello good afternoon, thank you po for informing me about this matter.
Nakalimutan ko pong tanggalin sa code. Noted po i will remove ito po.

God bless po and have a great day sir!
